version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    command: uvicorn frontend.app:app --host 0.0.0.0 --port 8001 --reload

  # Uncomment for separate frontend service if needed
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.frontend
  #   ports:
  #     - "8501:8501"
  #   environment:
  #     - BACKEND_URL=http://backend:8001
  #   depends_on:
  #     - backend
